title: "【LIFF/ミニアプリ】LINE×AWS×PayPayでテーブルオーダーを作ってみよう！ハンズオン"
summary: |-
  本資料は下記のハンズオンイベントで使用したものです。
  https://linedevelopercommunity.connpass.com/event/207867/
  
  あくまでもハンズオン用の資料であり、本番運用などを目的としたものではありません。
  みなさまのさらなる応用や発展の一助になれば幸いです。
  
  また、本資料は下記を参考にしてますのでご参照の上、ご利用いただければと思います。
  https://github.com/line/line-api-use-case-table-order

topics: ["line"]
published: true
price: 0
chapters:
  - 1-introduction
  - 2-create-line-messaging-api-channel
  - 3-create-line-login-channel
  - 4-setup-paypay-for-developers
  - 5-setup-aws-cloud9
  - 6-deploy-aws-backend
  - 7-deploy-aws-frontend
  - 8-validation
  - 9-clean-up
